# Generated by Django 3.1.2 on 2020-10-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='precio',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
